#!/bin/bash
 #Первый аргумент - название USB (sdb или sdc)
 #Второй аргумент - папка, с которой происходит синхронизация
 #Для работы необходимо создать файл <fname>.rules в /etc/udev/rules.d со следующим содержанием:
#KERNEL=="sdb", RUN+="~/MyPrograms/2.usb_new_files/usb_new /dev/sdb ~/usb1"
#KERNEL=="sdc", RUN+="~/MyPrograms/2.usb_new_files/usb_new /dev/sdc ~/usb2"
DIR="$(dirname $0)"
"$DIR/synch" "$($DIR/get_usb_path $1)" $2
